services:
  - type: web
    name: cortexgrc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cortexgrc:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
